#!/usr/bin/env bash

ln -s $PWD/.zshrc $HOME/.zshrc
ln -s $PWD/.zsh $HOME/.zsh

ln -s $PWD/.config/fastfetch $HOME/.config/fastfetch
ln -s $PWD/.config/kitty $HOME/.config/kitty

mkdir -p $HOME/.config/VSCodium/User
ln -s $PWD/.config/VSCodium/User/settings.json $HOME/.config/VSCodium/User/settings.json
